Repository PardeepKumar816/lets-start-flutter, pull requests merged in 2022-10, with the labels that each got.

#7 added a example of tabbar
  tabbar_example.dart
Labels: hacktoberfest, hacktoberfest-accepted

#8 Drawer with a setting icon and a search field
  drawer_example.dart
Labels: hacktoberfest, hacktoberfest-accepted

#13 temperature example
  temperatue_example
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#12 Accelerometer example
  Accelerometer_Example
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#11 Gesture on long press
  LongPress_Gesture
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#10 gesture on double tap
  DoubleTap_Gesture
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#14 resolved issues
  .idea/.gitignore
  .idea/lets-start-flutter.iml
  .idea/libraries/Dart_SDK.xml
  .idea/modules.xml
  .idea/vcs.xml
  Accelerometer_Example.dart
  DoubleTap_Gesture.dart
  LongPress_Gesture.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#16 resolved issue in double_tab_gesture
  code_example/lib/DoubleTap_Gesture.dart
Labels: bug, hacktoberfest, hacktoberfest-accepted

#17 resolved issue in onlong_pressed_gesture
  code_example/lib/LongPress_Gesture.dart
Labels: bug, hacktoberfest, hacktoberfest-accepted

#18 resolved issues in temperature example
  code_example/lib/Accelerometer_Example.dart
  code_example/lib/temperatue_example.dart
  code_example/pubspec.lock
  code_example/pubspec.yaml
Labels: bug, hacktoberfest, hacktoberfest-accepted

#19 create listviewbuilder example
  .idea/libraries/Dart_Packages.xml
  code_example/lib/Accelerometer_Example.dart
  code_example/lib/list_view_builder_example.dart
  code_example/lib/main.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#20 Hack
  code_example/lib/grid_view_widget.dart
  code_example/lib/text_with_more_button.dart
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#21 email field added
  code_example/lib/email_field.dart
  code_example/pubspec.lock
  code_example/pubspec.yaml
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#24 Vageta
  code_example/lib/bottom_navigation_bar.dart
  code_example/lib/otp_input_widget.dart
  code_example/lib/splash_screen.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#31 Added Google maps flutter package code example
  code_example/lib/costume_alert_dialogue.dart
  code_example/lib/google_maps_flutter_example.dart
  code_example/lib/url_launcher_example.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#28 create elevated button
  code_example/lib/ElevatedButton.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#27 routes.dart
  code_example/lib/Routes.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#25 Create on long press widget
  code_example/lib/OnLongPress.dart
Labels: hacktoberfest, hacktoberfest-accepted

#32 added circle button
  code_example/lib/circle_button.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#33 added iam useless app in flutter
  code_example/lib/i_am_useless.dart
Labels: hacktoberfest, hacktoberfest-accepted

#34 Add files via upload
  code_example/lib/contact_us.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 Create basicFlutterWidgets.dart
  code_example/lib/basicFlutterWidgets.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#36 Create Xylophone.dart
  code_example/lib/Xylophone.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#35 Create gridview
  code_example/lib/gridview
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#41 Create AssetImage.dart
  code_example/lib/AssetImage.dart
Labels: hacktoberfest, hacktoberfest-accepted

#40 Create dicee.dart
  code_example/lib/dicee.dart
Labels: hacktoberfest, hacktoberfest-accepted

#39 Create TextFields.dart
  code_example/lib/TextFields.dart
Labels: hacktoberfest, hacktoberfest-accepted

#38 Create providerExample.dart
  code_example/lib/providerExample.dart
Labels: hacktoberfest, hacktoberfest-accepted

#42 Added bubble sort using Dart
  bubble_sort.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#43 Create insertion_sort.dart
  insertion_sort.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#44 Create merge_sort.dart
  merge_sort.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#45 Create selection_sort.dart
  selection_sort.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#47 Create gui_calculator.dart
  gui_calculator.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
